### ISSUE TITLE
Duplicate mime type charset=utf-8 on Response Header

### ISSUE THREAD

**Issue by flobaader** [trallnag/prometheus-fastapi-instrumentator#16]
Hi,

thank you for the great library. I have ran into an issue when using the metrics endpoint. It seems like the response contains the charset mime-type twice, which makes it incompatible with some HTTP clients.

**Response Headers**
```
content-type: text/plain; version=0.0.4; charset=utf-8; charset=utf-8
```

I am using the docker image `tiangolo/uvicorn-gunicorn-fastapi:python3.8` and
```
fastapi==0.61.2
prometheus-fastapi-instrumentator==5.5.0
```
 Do you know how I can fix this issue?

**Comment by trallnag** [comment]
Hey @flobaader, thanks for raising this bug. I managed to reproduce it. Seems like the way I was creating the `Response` object was wrong:

```python
Response(generate_latest(registry), media_type=CONTENT_TYPE_LATEST)
```

I passed in the full content type as `media_type` and it seems like the respective charset is appended to it, resulting in duplication. Fixed in <https://github.com/trallnag/prometheus-fastapi-instrumentator/commit/5cf109e87c6a23ac5c1a271bc5b039d5ec84c8d0> and released with <https://github.com/trallnag/prometheus-fastapi-instrumentator/releases/tag/releases%2F5.5.1>
