### ISSUE TITLE
Test `test_expose_defaults` fails due to `NameError` after updating

### ISSUE THREAD

**Issue by trallnag** [trallnag/prometheus-fastapi-instrumentator#219]
Pull request #153 introduced new parameter `registry` to set Prometheus client registry. It also added two tests to cover this enhancement.

After running `poetry update` on commit 8cec83b4736fe98220cf30a4a9e7405ebbc060c8 the `test_expose_defaults` started to fail.

```
info = <prometheus_fastapi_instrumentator.metrics.Info object at 0x7f232b7433d0>

    def instrumentation(info: Info) -> None:
>       TOTAL.labels(info.method, info.modified_status, info.modified_handler).inc()
E       NameError: free variable 'TOTAL' referenced before assignment in enclosing scope

src/prometheus_fastapi_instrumentator/metrics.py:628: NameError
```

Before that it worked fine. It tried to debug it. The Prometheus client lib is complaining about duplicate metrics as excepted.

```
Duplicated timeseries in CollectorRegistry: {'http_requests_total', 'http_requests_created', 'http_requests'}
```

Problems start when updating starlette and fastapi

```
  • Updating starlette (0.22.0 -> 0.25.0)
  • Updating fastapi (0.88.0 -> 0.92.0)
```

**Comment by trallnag** [comment]
Hey @tiangolo, any idea what might have changed with the update that results in the test suddenly failing?

The hotfix seems to work (see PR) but would still be interesting to know

**Comment by frankie567** [comment]
Hey there 👋 

Came across this and I thought I would put my two cents in. I think this problem was introduced because since Starlette 0.24.0, the middleware stack is built only once when app starts (and not each time `add_middleware` is called like before). Here is the relevant PR: https://github.com/encode/starlette/pull/2017

IMHO, the fact that `test_expose_defaults` was passing was an happy consequence of side effects produced by the rebuild of the middleware stack. It shouldn't have passed like this, with the risk of having local variables undefined.

**Comment by dhodun** [comment]
This latest PR 220 fixed the issue in our environment:
https://github.com/trallnag/prometheus-fastapi-instrumentator/pull/220/files
